Update issue 339
RequestResponse-generator tests failing for 3.4.0 due to errors like:
  java.lang.NoClassDefFoundError: org/apache/xml/serializer/ExtendedContentHandler

Fixed by adding dependency to xalan:serializer in 3.4.0-dependencies pom.